---
root: true
parserOptions:
  ecmaVersion: 2022
  sourceType: script
env:
  node: true
  es6: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:editorconfig/all"
plugins:
  - "editorconfig"
ignorePatterns:
  - "dist"
rules:
  curly: "warn"
  eqeqeq: "warn"
  quotes: ["warn", "single"]
  sort-imports: ["error", {
        ignoreCase: false,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
        allowSeparatedGroups: false
    }]
