---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: stage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stage:
    runs-on: ubuntu-latest
    environment: staging
    name: Stage the project
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install node 22
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '22'
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d4688 # v6
        with:
          python-version: "3.13"

      - name: Cache pip repository
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Prepare python environment
        run: pip install -r requirements.txt

      - name: Build site
        run: mkdocs build

      - name: Install project modules
        run: npm ci

      - name: Lint source files
        run: npm run lint

      - name: Run unit tests and verify code coverage
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
